- name: 'apt-get update'
  hosts: localhost
  become: true
  become_method: sudo
  tasks:
    - apt:
        update_cache: yes
- name: 'install zsh and use as default shell'
  hosts: localhost
  vars_files: 
    - ./personal.yaml
  become: true
  become_method: sudo
  tasks:
    - apt:
        pkg:
          zsh
    - command: chsh {{ USER }} -s /usr/bin/zsh
    - command: echo ". $HOME/.asdf/asdf.sh" >> ~/.zshrc
- name: 'install asdf'
  hosts: localhost
  tasks:
    - ansible.builtin.git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: ~/.asdf
- name: config git
  hosts: localhost
  vars_files: 
    - ./personal.yaml
  tasks:
    - command: git config --global user.email ${{ EMAIL }}
    - command: git config --global user.name ${{ GITHUB_USERNAME }}
