-  name: 'apt-get update'
   hosts: localhost
   become: true
   become_method: sudo
   tasks:
       -  apt:
            update_cache: yes
-  name: 'install zsh and use as default shell'
   hosts: localhost
   become: true
   become_method: sudo
   tasks:
       -  apt:
            pkg:
              zsh
       -  command: chsh -s "$(which zsh)"
-  name: 'install build-essential'
   hosts: localhost
   become: true
   become_method: sudo
   tasks:
       -  apt:
            pkg:
            - build-essential
-  name: 'install docker essentials'
   hosts: localhost
   become: true
   become_method: sudo
   tasks:
       -  apt:
            pkg:
            - ca-certificates
            - curl
            - gnupg
            - lsb-release
