-  name: 'apt-get update'
   hosts: localhost
   become: true
   become_method: sudo
   tasks:
       -  apt:
            update_cache: yes
-  name: 'install zsh and use as default shell'
   hosts: localhost
   vars_files: 
       - ./personal.yaml
   become: true
   become_method: sudo
   tasks:
       -  apt:
            pkg:
              zsh
       -  command: chsh {{ USER }} -s /usr/bin/zsh

-  name: 'install build-essential'
   hosts: localhost
   become: true
   become_method: sudo
   tasks:
       -  apt:
            pkg:
            - build-essential
-  name: 'install docker essentials'
   hosts: localhost
   vars_files:
       - ./personal.yaml
   become: true
   become_method: sudo
   tasks:
       -  apt:
            pkg:
            - ca-certificates
            - curl
            - gnupg
            - lsb-release
       -  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
       -  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
       -  apt:
            pkg:
            - docker-ce
            - docker-ce-cli
            - containerd.io
       -  user: name={{ USER }}
                group=docker

-  name: 'install docker-compose'
   hosts: localhost
   become: true
   become_method: sudo
   tasks:
       - shell: curl -L https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
       - command: chmod +x /usr/local/bin/docker-compose

-  name: 'install kubectl'
   hosts: localhost
   become: true
   become_method: sudo
   tasks:
       - shell: curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
       - command: chmod +x ./kubectl
       - command: mv ./kubectl /usr/local/bin/kubectl

-  name: 'install minikube'
   hosts: localhost
   become: true
   become_method: sudo
   tasks:
       - shell: curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
       - command: install minikube-linux-amd64 /usr/local/bin/minikube
